[2016-06-14 12:14:12] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-14 12:14:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-14 12:14:13] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-14 12:15:58] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-14 12:15:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-14 12:15:58] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-14 12:20:06] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-14 12:20:06] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-14 12:20:06] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-14 12:20:44] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-14 12:20:44] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-14 12:20:44] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-14 12:22:14] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-14 12:22:14] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-14 12:22:14] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 08:27:33] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 08:27:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:27:33] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 08:27:35] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","variable":"hello","_route":"test"},"request_uri":"http://localhost/post/hello"} []
[2016-06-15 08:27:35] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:28:10] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","variable":"hello","_route":"test"},"request_uri":"http://localhost/post/hello"} []
[2016-06-15 08:28:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:29:38] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","variable":"hello","_route":"test"},"request_uri":"http://localhost/post/hello"} []
[2016-06-15 08:29:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:30:09] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","variable":"hello","_route":"test"},"request_uri":"http://localhost/post/hello"} []
[2016-06-15 08:30:09] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:31:29] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/post"} []
[2016-06-15 08:31:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:31:50] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/post"} []
[2016-06-15 08:31:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:32:13] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/post"} []
[2016-06-15 08:32:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:46:42] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/post"} []
[2016-06-15 08:46:42] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:55:45] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/post"} []
[2016-06-15 08:55:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:56:00] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/post"} []
[2016-06-15 08:56:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:56:28] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/post"} []
[2016-06-15 08:56:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:59:18] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/post"} []
[2016-06-15 08:59:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 08:59:36] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/post"} []
[2016-06-15 08:59:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:26:46] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "Class AppBundle\Util\TestController does not exist in C:\xampp\htdocs\symfony\courses\src\AppBundle/Controller/ (which is being imported from "C:\xampp\htdocs\symfony\courses\app/config\routing.yml")." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\Config\Loader\FileLoader.php line 133 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): Class AppBundle\\Util\\TestController does not exist in C:\\xampp\\htdocs\\symfony\\courses\\src\\AppBundle/Controller/ (which is being imported from \"C:\\xampp\\htdocs\\symfony\\courses\\app/config\\routing.yml\"). at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Config\\Loader\\FileLoader.php:133, ReflectionException(code: -1): Class AppBundle\\Util\\TestController does not exist at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Routing\\Loader\\AnnotationDirectoryLoader.php:52)"} []
[2016-06-15 09:28:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /crawling/home"" at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /crawling/home\" at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\symfony\\courses\\app\\cache\\test\\appTestUrlMatcher.php:163)"} []
[2016-06-15 09:28:43] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/test"} []
[2016-06-15 09:28:44] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:29:19] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\TestController::testAction","_route":"test"},"request_uri":"http://localhost/test"} []
[2016-06-15 09:29:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:33:00] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:33:01] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:33:01] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 09:33:50] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:33:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:33:50] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 09:35:19] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:35:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:35:19] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 09:35:56] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:35:56] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:35:56] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 09:39:33] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:39:34] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:39:34] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 09:51:49] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:51:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:51:49] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 09:54:44] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:54:44] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:54:44] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "test" as such route does not exist.") in "test.html.twig" at line 13." at C:\xampp\htdocs\symfony\courses\vendor\twig\twig\lib\Twig\Template.php line 402 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"test\" as such route does not exist.\") in \"test.html.twig\" at line 13. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\twig\\twig\\lib\\Twig\\Template.php:402, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"test\" as such route does not exist. at C:\\xampp\\htdocs\\symfony\\courses\\app\\cache\\test\\appTestUrlGenerator.php:54)"} []
[2016-06-15 09:55:26] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"categoryId":"4","_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:55:26] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:55:27] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "test" as such route does not exist.") in "test.html.twig" at line 13." at C:\xampp\htdocs\symfony\courses\vendor\twig\twig\lib\Twig\Template.php line 402 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"test\" as such route does not exist.\") in \"test.html.twig\" at line 13. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\twig\\twig\\lib\\Twig\\Template.php:402, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"test\" as such route does not exist. at C:\\xampp\\htdocs\\symfony\\courses\\app\\cache\\test\\appTestUrlGenerator.php:54)"} []
[2016-06-15 09:56:21] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:56:21] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:56:21] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "test" as such route does not exist.") in "test.html.twig" at line 13." at C:\xampp\htdocs\symfony\courses\vendor\twig\twig\lib\Twig\Template.php line 402 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"test\" as such route does not exist.\") in \"test.html.twig\" at line 13. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\twig\\twig\\lib\\Twig\\Template.php:402, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"test\" as such route does not exist. at C:\\xampp\\htdocs\\symfony\\courses\\app\\cache\\test\\appTestUrlGenerator.php:54)"} []
[2016-06-15 09:57:25] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:57:25] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:57:25] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "test" as such route does not exist.") in "test.html.twig" at line 13." at C:\xampp\htdocs\symfony\courses\vendor\twig\twig\lib\Twig\Template.php line 402 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"test\" as such route does not exist.\") in \"test.html.twig\" at line 13. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\twig\\twig\\lib\\Twig\\Template.php:402, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"test\" as such route does not exist. at C:\\xampp\\htdocs\\symfony\\courses\\app\\cache\\test\\appTestUrlGenerator.php:54)"} []
[2016-06-15 09:59:01] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm/4"} []
[2016-06-15 09:59:01] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 09:59:01] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "test" as such route does not exist.") in "test.html.twig" at line 13." at C:\xampp\htdocs\symfony\courses\vendor\twig\twig\lib\Twig\Template.php line 402 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"test\" as such route does not exist.\") in \"test.html.twig\" at line 13. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\twig\\twig\\lib\\Twig\\Template.php:402, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"test\" as such route does not exist. at C:\\xampp\\htdocs\\symfony\\courses\\app\\cache\\test\\appTestUrlGenerator.php:54)"} []
[2016-06-15 10:01:16] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/programm"} []
[2016-06-15 10:01:16] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:01:16] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "test" as such route does not exist.") in "test.html.twig" at line 13." at C:\xampp\htdocs\symfony\courses\vendor\twig\twig\lib\Twig\Template.php line 402 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"test\" as such route does not exist.\") in \"test.html.twig\" at line 13. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\twig\\twig\\lib\\Twig\\Template.php:402, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"test\" as such route does not exist. at C:\\xampp\\htdocs\\symfony\\courses\\app\\cache\\test\\appTestUrlGenerator.php:54)"} []
[2016-06-15 10:03:28] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test"} []
[2016-06-15 10:03:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:05:11] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:05:11] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:06:41] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:06:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:06:58] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:06:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:06:58] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 10:07:10] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:07:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:07:10] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 10:07:17] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:07:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:07:33] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:07:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:07:57] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:07:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:07:58] doctrine.DEBUG: SELECT c0_.id AS id_0, c0_.number AS number_1, c0_.name AS name_2, c0_.target_group AS target_group_3, c0_.price AS price_4, c0_.place AS place_5, c0_.description AS description_6, c0_.booked AS booked_7, c0_.available_place AS available_place_8, c1_.id AS id_9, c1_.name AS name_10, d2_.id AS id_11, d2_.date AS date_12, d2_.start AS start_13, d2_.end AS end_14, u3_.id AS id_15, u3_.anrede AS anrede_16, u3_.vorname AS vorname_17, u3_.name AS name_18, u3_.username AS username_19, u3_.email AS email_20, u3_.password AS password_21, u3_.roles AS roles_22, u3_.is_active AS is_active_23, c0_.categoryId AS categoryId_24, c0_.user_id AS user_id_25, d2_.course_id AS course_id_26 FROM course c0_ INNER JOIN category c1_ ON c0_.categoryId = c1_.id INNER JOIN date__time d2_ ON c0_.id = d2_.course_id INNER JOIN user_logdaten u3_ ON c0_.user_id = u3_.id WHERE c1_.id = ? ["4"] []
[2016-06-15 10:09:14] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:09:14] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:09:14] doctrine.DEBUG: SELECT c0_.id AS id_0, c0_.number AS number_1, c0_.name AS name_2, c0_.target_group AS target_group_3, c0_.price AS price_4, c0_.place AS place_5, c0_.description AS description_6, c0_.booked AS booked_7, c0_.available_place AS available_place_8, c1_.id AS id_9, c1_.name AS name_10, d2_.id AS id_11, d2_.date AS date_12, d2_.start AS start_13, d2_.end AS end_14, u3_.id AS id_15, u3_.anrede AS anrede_16, u3_.vorname AS vorname_17, u3_.name AS name_18, u3_.username AS username_19, u3_.email AS email_20, u3_.password AS password_21, u3_.roles AS roles_22, u3_.is_active AS is_active_23, c0_.categoryId AS categoryId_24, c0_.user_id AS user_id_25, d2_.course_id AS course_id_26 FROM course c0_ INNER JOIN category c1_ ON c0_.categoryId = c1_.id INNER JOIN date__time d2_ ON c0_.id = d2_.course_id INNER JOIN user_logdaten u3_ ON c0_.user_id = u3_.id WHERE c1_.id = ? ["4"] []
[2016-06-15 10:10:06] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:10:06] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:10:06] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 10:19:53] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:19:53] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:19:53] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 10:19:54] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:19:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:19:54] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 10:21:11] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:21:12] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:21:12] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 10:21:33] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:21:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:21:35] doctrine.DEBUG: SELECT c0_.id AS id_0, c0_.number AS number_1, c0_.name AS name_2, c0_.target_group AS target_group_3, c0_.price AS price_4, c0_.place AS place_5, c0_.description AS description_6, c0_.booked AS booked_7, c0_.available_place AS available_place_8, c1_.id AS id_9, c1_.name AS name_10, d2_.id AS id_11, d2_.date AS date_12, d2_.start AS start_13, d2_.end AS end_14, u3_.id AS id_15, u3_.anrede AS anrede_16, u3_.vorname AS vorname_17, u3_.name AS name_18, u3_.username AS username_19, u3_.email AS email_20, u3_.password AS password_21, u3_.roles AS roles_22, u3_.is_active AS is_active_23, c0_.categoryId AS categoryId_24, c0_.user_id AS user_id_25, d2_.course_id AS course_id_26 FROM course c0_ INNER JOIN category c1_ ON c0_.categoryId = c1_.id INNER JOIN date__time d2_ ON c0_.id = d2_.course_id INNER JOIN user_logdaten u3_ ON c0_.user_id = u3_.id WHERE c1_.id = ? ["4"] []
[2016-06-15 10:56:50] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:56:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:56:50] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
[2016-06-15 10:57:24] request.INFO: Matched route "app_course_showProgramByCategory". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"app_course_showProgramByCategory"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 10:57:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 10:57:26] doctrine.DEBUG: SELECT c0_.id AS id_0, c0_.number AS number_1, c0_.name AS name_2, c0_.target_group AS target_group_3, c0_.price AS price_4, c0_.place AS place_5, c0_.description AS description_6, c0_.booked AS booked_7, c0_.available_place AS available_place_8, c1_.id AS id_9, c1_.name AS name_10, d2_.id AS id_11, d2_.date AS date_12, d2_.start AS start_13, d2_.end AS end_14, u3_.id AS id_15, u3_.anrede AS anrede_16, u3_.vorname AS vorname_17, u3_.name AS name_18, u3_.username AS username_19, u3_.email AS email_20, u3_.password AS password_21, u3_.roles AS roles_22, u3_.is_active AS is_active_23, c0_.categoryId AS categoryId_24, c0_.user_id AS user_id_25, d2_.course_id AS course_id_26 FROM course c0_ INNER JOIN category c1_ ON c0_.categoryId = c1_.id INNER JOIN date__time d2_ ON c0_.id = d2_.course_id INNER JOIN user_logdaten u3_ ON c0_.user_id = u3_.id WHERE c1_.id = ? ["4"] []
[2016-06-15 11:04:56] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"test"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 11:04:56] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 11:04:56] doctrine.DEBUG: SELECT c0_.id AS id_0, c0_.number AS number_1, c0_.name AS name_2, c0_.target_group AS target_group_3, c0_.price AS price_4, c0_.place AS place_5, c0_.description AS description_6, c0_.booked AS booked_7, c0_.available_place AS available_place_8, c1_.id AS id_9, c1_.name AS name_10, d2_.id AS id_11, d2_.date AS date_12, d2_.start AS start_13, d2_.end AS end_14, u3_.id AS id_15, u3_.anrede AS anrede_16, u3_.vorname AS vorname_17, u3_.name AS name_18, u3_.username AS username_19, u3_.email AS email_20, u3_.password AS password_21, u3_.roles AS roles_22, u3_.is_active AS is_active_23, c0_.categoryId AS categoryId_24, c0_.user_id AS user_id_25, d2_.course_id AS course_id_26 FROM course c0_ INNER JOIN category c1_ ON c0_.categoryId = c1_.id INNER JOIN date__time d2_ ON c0_.id = d2_.course_id INNER JOIN user_logdaten u3_ ON c0_.user_id = u3_.id WHERE c1_.id = ? ["4"] []
[2016-06-15 11:05:10] request.INFO: Matched route "test". {"route_parameters":{"_controller":"AppBundle\\Controller\\CourseTestController::showProgramByCategoryAction","categoryId":"4","_route":"test"},"request_uri":"http://localhost/test/4"} []
[2016-06-15 11:05:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-06-15 11:05:10] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "C:\xampp\htdocs\symfony\courses\vendor\phpunit\phpunit\src\Util\Printer.php" at line 134." at C:\xampp\htdocs\symfony\courses\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 140 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"C:\\xampp\\htdocs\\symfony\\courses\\vendor\\phpunit\\phpunit\\src\\Util\\Printer.php\" at line 134. at C:\\xampp\\htdocs\\symfony\\courses\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage.php:140)"} []
